config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :tweets, only: [:index]
  resources :facebook, only: [:index]
  resources :instagram, only: [:index]
  resources :linkedin, only: [:index]
  resources :feeds, except: [:new]
  resources :menu, only: [:show]

end

app/models/menu.rb
class Menu
  require "#{Rails.root}/app/modules/RssGetter.rb"
  def initialize(url, options={})
    if options.values[0] == "NPR"
      @hash = RssGetter::NPR.new(url).to_hash
    elsif options.values[0] == "NYT"
      @hash = RssGetter::NYT.new(url).to_hash
    elsif options.values[0] == "TMZ"
      @hash = RssGetter::TMZ.new(url).to_hash
    elsif options.values[0] == "MISC"
      @hash = RssGetter::Links.new(url, options.values[1]).to_hash
    end
  end
end

app/views/menu/show.html.erb
<!-- Main Menu, slideout drawer style -->

<!-- npr feeds -->
<% npr = Menu.new("http://www.npr.org/rss/", {type: "NPR"}) %>
<% nprhash = npr.instance_values %>
<% nprlinks = nprhash.values %>

<!-- ny times feeds -->
<% nyt = Menu.new('http://www.nytimes.com/services/xml/rss/index.html', {type:"NYT"}) %>
<% nythash = nyt.instance_values %>
<% nytlinks = nythash.values %>

<!-- tmz feeds -->
<% tmz = Menu.new("http://www.tmz.com/feeds", {type: "TMZ"}) %>
<% tmzhash = tmz.instance_values %>
<% tmzlinks = tmzhash.values %>

<!-- USNEWS -->
<% usnews = Menu.new("http://www.usnews.com/info/features/rss-feeds", {type: "MISC", params: "a.rss"}) %>
<% usnewshash = usnews.instance_values %>
<% usnewslinks = usnewshash.values %>

<!-- USA.gov Science & Tech feeds -->
<% usagov_science = Menu.new("http://www.usa.gov/Topics/Reference-Shelf/Libraries/RSS-Library/Science.shtml", {type: "MISC", params: "ul.one_column_bullet li a"} ) %>
<% usagovsci_hash = usagov_science.instance_values %>
<% usagovsci_links = usagovsci_hash.values %>

<nav id="feeds-menu" class="off-canvas">
  <div class="feed-form">
    <h2>Add your own rss feed:</h2>
    <%= render 'feeds/form'  %>
  </div>
  <h2>Select a feed:</h2>
  <ul>
    <li>
      <a class="provider" href="javascript:void(0)" data-type="unit">NPR: Always On</a>
      <ul>
        <% nprlinks[0].each_pair do |k,v| %>
        <li><%= button_to "Add #{k}", feeds_path(feed: {url: v[0]}) , action: "create", class: 'btn btn-default' %></li>
        <% end %>
      </ul>
    </li>
    <li>
      <a class="provider" href="javascript:void(0)" data-type="unit">NY Times</a>
      <ul>
        <% nytlinks[0].each_pair do |k,v| %>
        <li><%= button_to "Add #{k}", feeds_path(feed: {url: v[0]}), action: "create", class: 'btn btn-default' %></li>
        <% end %>
      </ul>
    </li>
    <li>
      <a href="javascript:void(0)" class="provider" data-type="unit">TMZ</a>
      <ul>
        <% tmzlinks[0].each_pair do |k,v| %>
        <li><%= button_to "Add #{k}", feeds_path(feed: {url: v[0]}), action: "create", class: 'btn btn-default' %></li>
        <% end %>
      </ul>
    </li>
    <li>
      <a href="javascript:void(0)" class="provider" data-type="unit">US News &amp; World Report</a>
      <ul>
        <% usnewslinks[0].each_pair do |k,v| %>
        <li><%= button_to "Add #{k}", feeds_path(feed: {url: v[0]}), action: "create", class: 'btn btn-default' %></li>
        <% end %>
      </ul>
    </li>
    <li>
      <a href="javascript:void(0)" class="provider" data-type="unit">USA dot Gov Science &amp; Tech</a>
      <ul>
        <% usagovsci_links[0].each_pair do |k,v| %>
        <li><%= button_to "Add #{k}", feeds_path(feed: {url: v[0]}), action: "create", class: 'btn btn-default' %></li>
        <% end %>
      </ul>
    </li>
  </ul>
</nav>