config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :tweets, only: [:index]
  resources :facebook, only: [:index]
  resources :instagram, only: [:index]
  resources :linkedin, only: [:index]
  resources :feeds, except: [:new]
  resources :menu, only: [:show]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if User.all.length == 0
      redirect_to new_user_registration_path
    end
    if user_signed_in?
      @user = User.find(current_user)
      @user_feeds = Feed.get_user_feeds(current_user)
      @users = find_users(@user_feeds)
    else
      @users = User.includes(:feeds)
    end
  end

  private
  def find_users(array)
    array.map do |item|
      User.find(item.user_id).email
    end
  end
end

app/views/home/index.html.erb
<div class="container home-index-wrapper">
<% if user_signed_in? %>

  <% auths = UserAuthentication.all.select { |auth| auth.user_id == current_user.id } %>
  <% has_twitter = auths.select { |auth| auth.params.provider == "twitter" } %>
  <% has_linkedin = auths.select { |auth| auth.params.provider == "linkedin" } %>
  <% has_instagram = auths.select { |auth| auth.params.provider == "instagram" } %>

  <!-- twitter -->
  <% if has_twitter.length > 0 %>
    <%= link_to(tweets_path) do  %>
      <div class="grid_4 thumb twitter-thumb">
        <h3>Twitter</h3>
        <span class="twitter-icon"></span>
      </div>
    <% end %>
  <% else %>
    <div class="grid_4 thumb twitter-thumb">
      <%= link_to "Add Your Twitter Account", user_omniauth_authorize_path(:twitter) %>
    </div>
  <% end %>

  <% if has_linkedin.length > 0 %>
    <%= link_to(linkedin_index_path) do %>
      <div class="grid_4 thumb linkedin-thumb">
        <h3>Linked In</h3>
        <span class="linkedin-icon"></span>
      </div>
    <% end %>
  <% else %>
    <div class="grid_4 thumb linkedin-thumb">
      <%= link_to "Add Your Linked In Account", user_omniauth_authorize_path(:linkedin) %>
    </div>
  <% end %>

  <% if has_instagram.length > 0 %>
    <%= link_to(instagram_index_path) do %>
      <div class="grid_4 thumb instagram-thumb">
        <h3>Instagram</h3>
        <span class="instagram-icon"></span>
      </div>
    <% end %>
  <% else %>
    <div class="grid_4 thumb instagram-thumb">
      <%= link_to "Add Your Instagram Account", user_omniauth_authorize_path(:instagram) %>
    </div>
  <% end %>

  <!-- rss feeds -->
  <% if @user_feeds.length > 0  %>
    <% @user_feeds.each do |feed| %>
      <%= link_to(feed) do  %>
        <div class="grid_4 thumb feed-thumb">
          <h3><%= feed.title %></h3>
          <p>Added by: <%= @users[@user_feeds.index(feed)] %></p>
          <span class="feed-icon"></span>
        </div>
      <% end %>
    <% end %>
  <% end %>

<% else %>

  <!-- rss feeds for no logged in users -->
  <% @users.each do |user| %>
    <div class="grid_16">
      <h2><%= user.email %> added:</h3>
      <% user.feeds.each do |feed| %>
        <%= link_to(feed) do  %>
        <div class="grid_4 thumb feed-thumb">
          <h3><%= feed.title %></h3>
        </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>
</div>